
-- ==============================================================================
-- SCHEMA COMPLETO DO SUPABASE - PROFBIO UFJF-GV (Diretório Docente)
-- ==============================================================================
-- Este script cria todas as tabelas, relacionamentos, funções de segurança,
-- políticas de RLS, buckets de armazenamento (Storage) e popula os 19 docentes.
--
-- Como executar:
-- 1. Abra o painel do seu novo projeto no Supabase (https://supabase.com/dashboard)
-- 2. No menu lateral, acesse "SQL Editor" -> "New query"
-- 3. Cole todo este código e clique em "Run" (Executar)
-- ==============================================================================

-- 1. EXTENSÕES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 2. CRIAÇÃO DAS TABELAS
-- ==============================================================================

-- Tabela de Professores / Docentes
CREATE TABLE IF NOT EXISTS public.professors (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    title TEXT NOT NULL DEFAULT 'Docente PROFBIO',
    mini_bio TEXT DEFAULT '',
    lines_of_research TEXT[] DEFAULT '{}'::TEXT[],
    lattes_url TEXT DEFAULT '',
    public_email TEXT DEFAULT '',
    photo_url TEXT DEFAULT '',
    disponivel BOOLEAN NOT NULL DEFAULT TRUE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Tabela de Dissertações / Orientações
CREATE TABLE IF NOT EXISTS public.dissertations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    professor_id TEXT NOT NULL REFERENCES public.professors(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    student_name TEXT NOT NULL,
    year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
    status TEXT NOT NULL DEFAULT 'concluded' CHECK (status IN ('concluded', 'in_progress')),
    advisor_role TEXT NOT NULL DEFAULT 'orientador' CHECK (advisor_role IN ('orientador', 'coorientador')),
    pdf_url TEXT,
    summary TEXT DEFAULT '',
    podcast_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Tabela de Produtos Educacionais (artigos, jogos, cartilhas, etc.)
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dissertation_id UUID NOT NULL REFERENCES public.dissertations(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN (
        'Artigo', 'Conjunto de Dados', 'Repositório', 'Apresentação', 
        'Aplicativo', 'Livro', 'Revista em Quadrinhos', 'Jogo Digital', 
        'Sequência Didática', 'Automação de Processos Pedagógicos', 'Outro'
    )),
    url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Tabela de Candidaturas a Orientação
CREATE TABLE IF NOT EXISTS public.candidates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    professor_id TEXT NOT NULL REFERENCES public.professors(id) ON DELETE CASCADE,
    student_name TEXT NOT NULL,
    student_email TEXT NOT NULL,
    student_whatsapp TEXT DEFAULT '',
    lattes_url TEXT DEFAULT '',
    presentation_text TEXT DEFAULT '',
    photo_url TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Índices para alta performance
CREATE INDEX IF NOT EXISTS idx_professors_user_id ON public.professors(user_id);
CREATE INDEX IF NOT EXISTS idx_professors_name ON public.professors(name);
CREATE INDEX IF NOT EXISTS idx_dissertations_professor_id ON public.dissertations(professor_id);
CREATE INDEX IF NOT EXISTS idx_dissertations_year ON public.dissertations(year DESC);
CREATE INDEX IF NOT EXISTS idx_products_dissertation_id ON public.products(dissertation_id);
CREATE INDEX IF NOT EXISTS idx_candidates_professor_id ON public.candidates(professor_id);

-- ==============================================================================
-- 3. FUNÇÃO AUXILIAR DE SEGURANÇA (ADMIN)
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.professors
    WHERE user_id = auth.uid() AND is_admin = TRUE
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- ==============================================================================
-- 4. POLÍTICAS DE ROW LEVEL SECURITY (RLS)
-- ==============================================================================

ALTER TABLE public.professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dissertations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;

-- Políticas para professors
DROP POLICY IF EXISTS "Professores sao visiveis publicamente" ON public.professors;
CREATE POLICY "Professores sao visiveis publicamente" 
ON public.professors FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Docentes ou Admins podem atualizar perfil" ON public.professors;
CREATE POLICY "Docentes ou Admins podem atualizar perfil" 
ON public.professors FOR UPDATE TO authenticated 
USING (
  user_id = auth.uid() OR public.is_admin() = true
)
WITH CHECK (
  user_id = auth.uid() OR public.is_admin() = true
);

DROP POLICY IF EXISTS "Admins podem inserir novos docentes" ON public.professors;
CREATE POLICY "Admins podem inserir novos docentes" 
ON public.professors FOR INSERT TO authenticated 
WITH CHECK (public.is_admin() = true);

-- Políticas para dissertations
DROP POLICY IF EXISTS "Dissertacoes sao visiveis publicamente" ON public.dissertations;
CREATE POLICY "Dissertacoes sao visiveis publicamente" 
ON public.dissertations FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Docentes ou Admins gerenciam dissertacoes" ON public.dissertations;
CREATE POLICY "Docentes ou Admins gerenciam dissertacoes" 
ON public.dissertations FOR ALL TO authenticated 
USING (
  professor_id IN (SELECT id FROM public.professors WHERE user_id = auth.uid()) OR public.is_admin() = true
)
WITH CHECK (
  professor_id IN (SELECT id FROM public.professors WHERE user_id = auth.uid()) OR public.is_admin() = true
);

-- Políticas para products
DROP POLICY IF EXISTS "Produtos sao visiveis publicamente" ON public.products;
CREATE POLICY "Produtos sao visiveis publicamente" 
ON public.products FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Docentes ou Admins gerenciam produtos" ON public.products;
CREATE POLICY "Docentes ou Admins gerenciam produtos" 
ON public.products FOR ALL TO authenticated 
USING (
  dissertation_id IN (
    SELECT d.id FROM public.dissertations d
    WHERE d.professor_id IN (SELECT p.id FROM public.professors p WHERE p.user_id = auth.uid())
       OR public.is_admin() = true
  )
)
WITH CHECK (
  dissertation_id IN (
    SELECT d.id FROM public.dissertations d
    WHERE d.professor_id IN (SELECT p.id FROM public.professors p WHERE p.user_id = auth.uid())
       OR public.is_admin() = true
  )
);

-- Políticas para candidates
DROP POLICY IF EXISTS "Qualquer candidato pode enviar inscricao" ON public.candidates;
CREATE POLICY "Qualquer candidato pode enviar inscricao" 
ON public.candidates FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Docente responsavel ou Admin pode ver e atualizar candidatos" ON public.candidates;
CREATE POLICY "Docente responsavel ou Admin pode ver e atualizar candidatos" 
ON public.candidates FOR ALL TO authenticated 
USING (
  professor_id IN (SELECT id FROM public.professors WHERE user_id = auth.uid()) OR public.is_admin() = true
)
WITH CHECK (
  professor_id IN (SELECT id FROM public.professors WHERE user_id = auth.uid()) OR public.is_admin() = true
);

-- ==============================================================================
-- 5. BUCKETS DE STORAGE (ARQUIVOS / FOTOS / AUDIOS)
-- ==============================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES 
    ('avatars', 'avatars', true),
    ('pdfs', 'pdfs', true),
    ('podcasts', 'podcasts', true),
    ('candidate_photos', 'candidate_photos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de Storage: Acesso público para leitura
DROP POLICY IF EXISTS "Acesso publico para leitura de arquivos" ON storage.objects;
CREATE POLICY "Acesso publico para leitura de arquivos"
ON storage.objects FOR SELECT
USING (bucket_id IN ('avatars', 'pdfs', 'podcasts', 'candidate_photos'));

-- Upload de fotos por candidatos (público/anônimo)
DROP POLICY IF EXISTS "Upload publico de fotos de candidatos" ON storage.objects;
CREATE POLICY "Upload publico de fotos de candidatos"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'candidate_photos');

-- Upload e gerenciamento por docentes autenticados e admins
DROP POLICY IF EXISTS "Docentes e Admins gerenciam arquivos do sistema" ON storage.objects;
CREATE POLICY "Docentes e Admins gerenciam arquivos do sistema"
ON storage.objects FOR ALL TO authenticated
USING (bucket_id IN ('avatars', 'pdfs', 'podcasts', 'candidate_photos'))
WITH CHECK (bucket_id IN ('avatars', 'pdfs', 'podcasts', 'candidate_photos'));

-- ==============================================================================
-- 6. POPULAR DADOS INICIAIS (DOCENTES DO PROFBIO UFJF-GV)
-- ==============================================================================

INSERT INTO public.professors (
    id, name, title, mini_bio, lines_of_research, lattes_url, public_email, photo_url, disponivel, is_admin
) VALUES
(
    'p1',
    'Antônio Frederico de F. Gomides',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'frederico.gomides@ufjf.br',
    'https://ui-avatars.com/api/?name=Antonio+Frederico&background=034C83&color=fff',
    true,
    false
),
(
    'p2',
    'Carla da Silva Machado',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'carladasilvamachado@gmail.com',
    'https://ui-avatars.com/api/?name=Carla+Machado&background=034C83&color=fff',
    true,
    false
),
(
    'p3',
    'Cibele Velloso Rodrigues',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'cibele.velloso@ufjf.br',
    'https://ui-avatars.com/api/?name=Cibele+Rodrigues&background=034C83&color=fff',
    true,
    false
),
(
    'p4',
    'Dirce Ribeiro de Oliveira',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'dirce.oliveira@ufjf.br',
    'https://ui-avatars.com/api/?name=Dirce+Oliveira&background=034C83&color=fff',
    true,
    false
),
(
    'p5',
    'Fábio Alessandro Pieri',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'fabio.pieri@ufjf.br',
    'https://ui-avatars.com/api/?name=Fabio+Pieri&background=034C83&color=fff',
    true,
    false
),
(
    'p6',
    'Fernanda Souza de O. Assis',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'fernandabqi@gmail.com',
    'https://ui-avatars.com/api/?name=Fernanda+Assis&background=034C83&color=fff',
    true,
    false
),
(
    'p7',
    'Girley F. M. de Assis',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'girley.francisco@ufjf.br',
    'https://ui-avatars.com/api/?name=Girley+Assis&background=034C83&color=fff',
    true,
    false
),
(
    'p8',
    'Ione Maria de Matos',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'ione.matos@ufjf.br',
    'https://ui-avatars.com/api/?name=Ione+Matos&background=034C83&color=fff',
    true,
    false
),
(
    'p9',
    'João Eustáquio Antunes',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'joao.antunes@ufjf.br',
    'https://ui-avatars.com/api/?name=Joao+Antunes&background=034C83&color=fff',
    true,
    false
),
(
    'p10',
    'Leonardo Mees',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'leonardo.mees@ufjf.br',
    'https://ui-avatars.com/api/?name=Leonardo+Mees&background=034C83&color=fff',
    true,
    false
),
(
    'p11',
    'Mabel Suca Salas',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'mabel.salas@ufjf.br',
    'https://ui-avatars.com/api/?name=Mabel+Salas&background=034C83&color=fff',
    true,
    false
),
(
    'p12',
    'Maísa Silva',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'maisa.silva@ufjf.br',
    'https://ui-avatars.com/api/?name=Maisa+Silva&background=034C83&color=fff',
    true,
    false
),
(
    'p13',
    'Marcelo Nagem V. de Oliveira',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'nagem7@gmail.com',
    'https://ui-avatars.com/api/?name=Marcelo+Nagem&background=034C83&color=fff',
    true,
    false
),
(
    'p14',
    'Maria Gabriela P. Bicalho',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'maria.gabriela@ufjf.br',
    'https://ui-avatars.com/api/?name=Maria+Gabriela&background=034C83&color=fff',
    true,
    false
),
(
    'p15',
    'Michelle Bueno de M. P. Antunes',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'michelle.antunes@ufjf.br',
    'https://ui-avatars.com/api/?name=Michelle+Antunes&background=034C83&color=fff',
    true,
    false
),
(
    'p16',
    'Renata Bernardes Faria Campos',
    'Docente PROFBIO',
    'Doutora em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'rbfcampos@gmail.com',
    'https://ui-avatars.com/api/?name=Renata+Campos&background=034C83&color=fff',
    true,
    false
),
(
    'p17',
    'Roberto Queiroga Lautner',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'robertoql@gmail.com',
    'https://ui-avatars.com/api/?name=Roberto+Lautner&background=034C83&color=fff',
    true,
    false
),
(
    'p18',
    'Thiago Martins Santos',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'thiagomartinsantos@yahoo.com.br',
    'https://ui-avatars.com/api/?name=Thiago+Santos&background=034C83&color=fff',
    true,
    false
),
(
    'p19',
    'Márcio Souza',
    'Docente PROFBIO',
    'Doutor em Biologia. Atua no PROFBIO UFJF-GV.',
    ARRAY['Ensino de Biologia'],
    'http://lattes.cnpq.br/',
    'marcio.souza@ufjf.br',
    'https://ui-avatars.com/api/?name=Marcio+Souza&background=034C83&color=fff',
    true,
    false
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    mini_bio = EXCLUDED.mini_bio,
    lines_of_research = EXCLUDED.lines_of_research,
    lattes_url = EXCLUDED.lattes_url,
    public_email = EXCLUDED.public_email,
    photo_url = EXCLUDED.photo_url,
    disponivel = EXCLUDED.disponivel;

-- ==============================================================================
-- DICA: VINCULAR USUÁRIO DO SUPABASE AUTH A UM PROFESSOR OU TORNAR ADMIN
-- ==============================================================================
-- Depois de cadastrar um usuário no Supabase Auth com o email do professor:
-- UPDATE public.professors 
-- SET user_id = 'ID-DO-USUARIO-AUTH-AQUI', is_admin = true 
-- WHERE public_email = 'marcio.souza@ufjf.br';

